# Generated by Django 5.0.4 on 2024-05-24 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Npc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('weight', models.FloatField()),
                ('inventory', models.CharField(max_length=200)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
